# This workflow will build, test, measure coverage, and pack the library.

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Test with coverage
      run: dotnet test --configuration Release --no-restore --verbosity normal -p:ContinuousIntegrationBuild=true
    - name: Pack
      run: dotnet pack StringExtensionLibrary/StringExtensionLibrary.csproj --configuration Release --no-restore --output ./nupkg -p:ContinuousIntegrationBuild=true
